version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: artio
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: artio
      DB_PASSWORD: 1234
      DB_NAME: db
    command: [ "dotnet", "BulkyWeb.dll" ]

volumes:
  db_data:
